### ISSUE TITLE
为啥会出现这个问题？

### ISSUE THREAD

**Issue by airnever** [ohdarling/virtual-ldap#3]
如题，求解我这边使用钉钉下载下来的数据，运行LDAP报以下错误，
{"name":"ldapjs","component":"client","hostname":"ubuntu","pid":114024,"level":50,"msg":"192.168.118.1:58652::21 uncaught exception: InvalidDistinguishedNameError: ou=互联网+电力营销—数据支撑团队,ou=信息化建设6,ou=营销业务组,ou=信息服务中心,ou=staff,ou=groups,o=example,dc=example,dc=com\n    at invalidDN (/home/tiantiansaid/virtual-ldap-b11af3c24f46eef21b2dd700be423dfcbf472bc0/node_modules/ldapjs/lib/dn.js:10:11)\n    at parseAttrType (/home/tiantiansaid/virtual-ldap-b11af3c24f46eef21b2dd700be423dfcbf472bc0/node_modules/ldapjs/lib/dn.js:230:13)\n    at parseRdn (/home/tiantiansaid/virtual-ldap-b11af3c24f46eef21b2dd700be423dfcbf472bc0/node_modules/ldapjs/lib/dn.js:184:18)\n    at parse (/home/tiantiansaid/virtual-ldap-b11af3c24f46eef21b2dd700be423dfcbf472bc0/node_modules/ldapjs/lib/dn.js:308:13)\n    at filter.entry (/home/tiantiansaid/virtual-ldap-b11af3c24f46eef21b2dd700be423dfcbf472bc0/lib/server.js:141:25)\n    at Array.filter (<anonymous>)\n    at Server.server.search (/home/tiantiansaid/virtual-ldap-b11af3c24f46eef21b2dd700be423dfcbf472bc0/lib/server.js:140:7)\n    at /home/tiantiansaid/virtual-ldap-b11af3c24f46eef21b2dd700be423dfcbf472bc0/node_modules/ldapjs/lib/server.js:425:40\n    at Server.authorize (/home/tiantiansaid/virtual-ldap-b11af3c24f46eef21b2dd700be423dfcbf472bc0/lib/server.js:68:12)\n    at /home/tiantiansaid/virtual-ldap-b11af3c24f46eef21b2dd700be423dfcbf472bc0/node_modules/ldapjs/lib/server.js:425:40","time":"2020-09-07T09:10:29.318Z","v":0}
期待您的回复

**Comment by ohdarling** [comment]
看样子是由于部门名称带特殊字符导致的

**Comment by ohdarling** [comment]
DN 里不能出现 + 号，可以先尝试修改组织名来避免这个问题
